services:

  redis:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_IMGK}
    container_name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:6379
    environment:
      REDIS_ROOT_USER: ${REDIS_ROOT_USER}
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_APP_USER: ${REDIS_APP_USER}
      REDIS_APP_PASSWORD: ${REDIS_APP_PASSWORD}
    volumes:
      - ${COMPOSE_PROJECT_BIND}:/data
    deploy:
      resources:
        limits:
          memory: ${COMPOSE_PROJECT_MEM}
    tty: true
    restart: unless-stopped
